GET http://localhost:8080/public
Accept: application/json

###
POST http://localhost:8080/public
Content-Type: application/json

{}

###
GET http://localhost:8080/protected
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8080/protected
Accept: application/json
Cookie: JSESSIONID=572DFE9EE32FD4CF64EC8478BAC5817F; Path=/; HttpOnly

###
GET http://localhost:8080/protected
Accept: application/json

###